# Generated by Django 2.2 on 2019-04-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAmazonSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, null=True)),
                ('week_of', models.TextField(blank=True, null=True)),
                ('vr_units', models.FloatField(blank=True, null=True)),
                ('tph', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_amazon_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendorReturnDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.TextField(blank=True, null=True)),
                ('week_of', models.TextField(blank=True, null=True)),
                ('vr_units', models.FloatField(blank=True, null=True)),
                ('tph', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_vendor_return_detail',
                'managed': True,
            },
        ),
    ]
